# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antennatype',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antenna_types_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antennatype',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antenna_types_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astronaut',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astronauts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astronaut',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astronauts_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attitudecontrolsystem',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attitudecontrolsystem',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acs_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compound',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounds_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compound',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounds_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooling',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooling_methods_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooling',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coolig_methods_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crewedmission',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crewed_missions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crewedmission',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crewed_missions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electricitysource',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_sources_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electricitysource',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_sources_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engine',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engines_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engine',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engines_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidancesystem',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_systems_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guidancesystem',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_systems_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heatshieldmaterial',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heatshield_materials_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heatshieldmaterial',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heatshield_materials_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='igniter',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='igniters_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='igniter',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='igniters_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='injector',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injectors_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='injector',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injectors_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instrument',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instrument',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landingsolution',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_solutions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landingsolution',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_solutions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='launchfacility',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_facilities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='launchfacility',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_facilities_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lifesupporttype',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lss_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lifesupporttype',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lss_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missiontarget',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_targets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missiontarget',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_targets_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nozzlematerial',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nozzle_materials_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nozzlematerial',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nozzle_materials_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nozzletype',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nozzle_types_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nozzletype',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nozzle_types_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='powercycle',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_cycles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='powercycle',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_cycles_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propellantmix',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propellant_mixes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propellantmix',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propellant_mixes_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rocket',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rockets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rocket',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rockets_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rocketseries',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rocket_series_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rocketseries',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rocket_series_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_roles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_roles_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacecraft',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spacecraft_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacecraft',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spacecraft_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagerole',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_roles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagerole',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_roles_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tankconstruction',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_constructions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tankconstruction',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_constructions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tankmaterial',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_materials_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tankmaterial',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_materials_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
