# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170325_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
