# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_compound_variety_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='role',
            field=models.BooleanField(choices=[(True, 'Fuel'), (False, 'Oxidizer')]),
        ),
    ]
