# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170325_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compound',
            name='chem_formula',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
