# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_fueloxidizermix_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropellantMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=30)),
                ('hypergolic', models.BooleanField(default=False)),
                ('specific_impulse', models.PositiveIntegerField()),
                ('specific_impulse_sl', models.PositiveIntegerField(blank=True, null=True)),
                ('optimum_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('combustion_temp', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('propellants', models.ManyToManyField(to='catalog.Compound')),
            ],
        ),
        migrations.RemoveField(
            model_name='fueloxidizermix',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='fueloxidizermix',
            name='oxidizer',
        ),
        migrations.AlterField(
            model_name='engine',
            name='propellants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.PropellantMix'),
        ),
        migrations.DeleteModel(
            name='FuelOxidizerMix',
        ),
    ]
