# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170325_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='abbreviation',
        ),
        migrations.AddField(
            model_name='compound',
            name='also_known_as',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
