# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170325_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='propellantmix',
            name='characteristic_velocity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
