# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_propellantmix_characteristic_velocity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='chem_formula',
            field=models.CharField(blank=True, max_length=30, verbose_name='chemical formula'),
        ),
        migrations.AlterField(
            model_name='propellantmix',
            name='combustion_temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='combustion temperature'),
        ),
        migrations.AlterField(
            model_name='propellantmix',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propellantmix',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='num_flights',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='number of flights'),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='aux_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spacecraft_aux', to='catalog.Engine', verbose_name='auxilliary engine'),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='num_aux_engines',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='number of auxilliary engines'),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='num_flights',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='number of flights'),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='num_main_engines',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number of main engines'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='aux_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_aux', to='catalog.Engine', verbose_name='auxilliary engine'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='num_aux_engines',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='number of auxilliary engines'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='num_main_engines',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number of main engines'),
        ),
    ]
