# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170325_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooling',
            options={'verbose_name': 'Cooling system', 'verbose_name_plural': 'Cooling systems'},
        ),
        migrations.AlterModelOptions(
            name='launchfacility',
            options={'verbose_name_plural': 'Launch facilities'},
        ),
        migrations.AlterModelOptions(
            name='propellantmix',
            options={'verbose_name_plural': 'Propellant mixes'},
        ),
        migrations.AlterModelOptions(
            name='rocketseries',
            options={'verbose_name_plural': 'Rocket series'},
        ),
    ]
