# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20170326_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='successor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer', verbose_name='predecessor'),
        ),
    ]
