# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20170326_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='gimbal_range',
        ),
        migrations.AddField(
            model_name='engine',
            name='combustion_chambers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stage',
            name='main_gimbal_pitch_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='main_gimbal_pitch_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='main_gimbal_yaw_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='main_gimbal_yaw_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
