# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20170326_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='dry_weight',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='fueled_weight',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stage',
            name='dry_weight',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='fuel_weight',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='fueled_weight',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stage',
            name='oxidizer_weight',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
