# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20170326_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.StageRole'),
        ),
    ]
