# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20170326_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heatshieldmaterial',
            old_name='chem_formula',
            new_name='chemical_formula',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='chem_formula',
        ),
        migrations.AddField(
            model_name='compound',
            name='chemical_formula',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
