# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20170326_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='fairing_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rocket',
            name='fairing_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
