# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20170326_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionTarget',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sources', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='missiontargets/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mission',
            name='target',
        ),
        migrations.AddField(
            model_name='mission',
            name='targets',
            field=models.ManyToManyField(to='catalog.MissionTarget'),
        ),
    ]
