# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20170326_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propellantmix',
            name='combustion_temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='combustion                                           temperature'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='num_flights',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='number of                                                    flights'),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='num_aux_engines',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='number                                                        of auxilliary engines'),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='num_flights',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='number of                                                    flights'),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='num_main_engines',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number                                                         of main engines'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='num_aux_engines',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='number                                                        of auxilliary engines'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='num_main_engines',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number                                                        of main engines'),
        ),
    ]
