# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20170326_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antennatype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='astronaut',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='attitudecontrolsystem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='compound',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='crewedmission',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='electricitysource',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='guidancesystem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='heatshieldmaterial',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='igniter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='injector',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='landingsolution',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='lifesupporttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='missiontarget',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='nozzlematerial',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='nozzletype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='powercycle',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stagerole',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tankconstruction',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tankmaterial',
            options={'ordering': ['name']},
        ),
    ]
